name: image_crop
description: A flutter plugin to crop image on iOS and Android. It processes image files off main thread natively. The plugin provides a Crop widget to display image cropping to a user.
version: 0.2.0
author: Volodymyr Lykhonis <vladimirlichonos@gmail.com>
homepage: https://github.com/VolodymyrLykhonis/image_crop

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.0.7
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.lykhonis.imagecrop
    pluginClass: ImageCropPlugin
